### ISSUE TITLE
Download job exceptions

### ISSUE THREAD

**Issue by TimothyBolton** [Microsoft/Recurring-Integrations-Scheduler#71] opened 2018-11-06 07:03 UTC
I have 4 export data entities setup for the same entity with different filters with incremental refresh setup. These 4 data jobs appear to be working correctly, but I keep getting the follow error in the event log.

Quartz.Core.JobRunShell - Job Download jobs.UAT_MTS_NZ_APInvResponse threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Download job: Download jobs.UAT_MTS_NZ_APInvResponse failed ---> System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.UriBuilder..ctor(String uri)
   at RecurringIntegrationsScheduler.Job.Download.<Process>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.UriBuilder..ctor(String uri)
   at RecurringIntegrationsScheduler.Job.Download.<Process>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Download.<Execute>d__12.MoveNext()] 

I'm not exactly sure what the cause of this error is, but I think it has something to do with the 4 data jobs of same entity.

This is system is 8.04 PU20 using RIS 2.6

Thanks

Tim

**Comment by TomekMelissa** [comment] 2018-11-06 11:37
First of all try to use export job instead of download. Second, this is most likely caused by D365 not responding correctly. You should investigate on that side with MS Support.

**Comment by TimothyBolton** [comment] 2018-11-07 04:45
Hi Tomek,

Thanks for replying, I tried the export job rather than download, and it appears to stay permanently 'Blocked', however it appears to generates the export files, it just takes a long time. Is this expected behavior?

**Comment by TomekMelissa** [comment] 2018-11-07 08:09
"Blocked" is a status of a trigger. It is blocked so no new instance of the job will be fired until the running one is finished. Export job is sending a request for data first. Then D365 is preparing the data and saves the file in the blob storage. RIS is asking if it is ready using status check request. This request is executed based on an interval defined in job definition (status check interval). By default it is every five minute (300 sec.) You can change its value (lowest value allowed is 5 sec.) 
So export job will run (trigger will be in Blocked state) for five minutes usually if you do not change interval value.

**Comment by TimothyBolton** [comment] 2018-11-13 09:01
Hi,

I keep getting this error over and over again in AX-ODataService for a series export jobs
Exception occurred while executing action GetExecutionSummaryStatus on Entity  DataManagementDefinitionGroup: Execution details were not found for execution  id:  RIS_???_AU_GLResponse-2018-11-13_18-45-00-66438b3f-2813-43dc-8609-1c30283c425a

But I don't get any errors in 'Recurring Integrations Scheduler' event viewer.

Thanks

Tim

**Comment by TomekMelissa** [comment] 2018-11-13 14:33
Why do you have question marks in the data project name?

**Comment by TimothyBolton** [comment] 2018-11-13 21:30
The question marks are not significant, I don't have question marks in my job name.

**Comment by TimothyBolton** [comment] 2018-11-16 01:41
Hi,

Using the export data job instead of the download appears to create other issues with blocking/hanging when using 4 different export jobs of the same base entity at the same time. Certain jobs seem to hang forever. The only way I could get them working again, was to try and restart RIS service. This however, didn't work as wouldn't stop, so I had to end task quartz. I've changed the export process so that the 4 different export jobs run on a different time schedule, allowing them to finish without the blocking/hanging. This approach so far seems to work.

Thanks

Tim

**Comment by TimothyBolton** [comment] 2018-11-20 04:29
Hi,

I've also logged a request to Microsoft regarding this issue, as it seems that sometimes execution ID's can get lost with the asynchronous calls, where an execution is returned to RIS, but never created in 365.

RIS then continues to check the status of the execution, but it will never find it as it was never successfully created. So it keeps polling and polling for status forever.

eg. 
RecurringIntegrationsScheduler.Job.Export - Job: MTS_AU.UAT_MTS_Shared_Response Checking if export is completed. Try: 121. Status: Bad request

121 tries to check status

Thanks

Tim

**Comment by TomekMelissa** [comment] 2018-11-20 10:33
It is not forever. It will query 1000 times the status check interval defined in job definition. I am aware of this behavior of D365, but it needs to be solved there.

**Comment by Hesel** [comment] 2018-11-20 11:57
Just wanted to chime in: I'm seeing the same behavior, but I'm not using RIS. The code I'm using is based on the same API for DataPackage export.
Sometimes D365 reports back with an execution Id which does not exists. I'm not seeing any releation between which DataEntities are used. To me it looks like D365 somehow fumbels the creation of the ExecutionJob after having reported the ExecutionId.

The D365 is a 8.1 Update20

The JSON reply is:
	```
"error": {
		"code": "",
		"message": "An error has occurred.",
		"innererror": {
			"message": "Exception occurred while executing action GetExecutionSummaryStatus on Entity DataManagementDefinitionGroup: Execution details were not found for execution id: ExportPackage-11/15/2018 02:57:10 pm",
			"type": "System.InvalidOperationException",
			"stacktrace": "   at Microsoft.Dynamics.Platform.Integration.Services.OData.Action.ActionInvokable.Invoke()\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateProcessor.ActionInvocation(ChangeOperationContext context, ActionInvokable action)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.<>c__DisplayClass13_0.<ScheduleInvokable>b__0(ChangeOperationContext context)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActionsInCompanyContext(IEnumerable`1 actionList, ChangeOperationContext operationContext)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.ChangeInfo.ExecuteActions(ChangeOperationContext context)\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.Update.UpdateManager.SaveChanges()\r\n   at Microsoft.Dynamics.Platform.Integration.Services.OData.AxODataDelegatingHandler.<SaveChangesAsync>d__2.MoveNext()"
		}
	}
```

**Comment by TomekMelissa** [comment] 2018-11-20 13:21
Thank you @Hesel 
@TimothyBolton You can request to set flighting flag **DMFExportToPackageForceSync**. It will enforce synchronous call on exports. It will keep first export request alive until the export is finished and first status check request will be successful.

**Comment by Hesel** [comment] 2018-11-22 12:51
A followup:
I've tested the same setup against two different version of D365. If you provide a wrong/not-existing DefinitionGroupId the response is different depending on the D365-version.

Non-Exising DataJob name - 7.3:
Exception occurred while executing action ExportToPackage on Entity DataManagementDefinitionGroup: Data project _[NotExising job name]_ does not exist.

Non-Exising DataJob name - 8.1:
Exception occurred while executing action GetExecutionSummaryStatus on Entity DataManagementDefinitionGroup: Execution details were not found for execution id: ExportPackage-11/22/2018 12:23:30 pm

(These two responses were produced with the exact same code, only different D365 targets)

So in 8.1, you can actually request an ExportToPackage with a non-exsiting Data Job name, and get an ExecutionId back which is bogus.

**Comment by Hesel** [comment] 2018-12-03 15:58
@KateDL I don't think that multiple parallel exports are supported. At least not from my experience. If there is a solution to that particular issue, I would love to know it.

**Comment by KateDL** [comment] 2018-12-03 16:46
Is there any chance to start multiple parallel exports, e.g. with several standalone schedulers?

**Closed** 2019-03-19 17:26 UTC
